#server:
#  port: 8085



camel:
  component:
    servlet:
      mapping:
        contextPath: /api/*

spring:
  application:
    name: camel-demo
#  mvc:
#    servlet:
#      path: /camel

#endpoints:
#  enabled: true
#  health:
#    enabled: true
#quickstart:
#  generateOrderPeriod: 10s
#  processOrderPeriod: 30s